### ISSUE TITLE
QUESTION: Middleware parameters

### ISSUE THREAD

**Issue by joshhornby** [yarcub/twiliojs-redux#1]
Hi @yarcub 

Thanks for writing this package, it has been very useful in our Twilio integration.

I have a question about the `middleware` method, the second parameter expects a `Promise`, in most real world use cases I can imagine an API call to get a token will need some data already stored in the state (auth token of some kind), do you have any suggestions on the best way on how to access the data in the `store` inside this function? Or if this is not possible maybe we can discuss improving the public API for the `middleware` method?

I hope to be using this package in production so would really appreciate any time you can spare to help me out.

Thanks

**Comment by yarcub** [comment]
Hi @joshhornby!

> Thanks for writing this package, it has been very useful in our Twilio integration.

Thanks, glad to hear that. 😃  🎉 

> I hope to be using this package in production so would really appreciate any time you can spare to help me out.

As i say in [README](https://github.com/yarcub/twiliojs-redux/blob/master/README.md), this module was the outcome of a learning experience and i'm not really activelly mantaining it. Please take that into account when depending on this package.

Anyhow, really glad that it's useful for anyone. PRs are always welcome and i'm open to add write access contributors if someone wants to actively maintain it.

I've just added a [Greenkeeper](https://greenkeeper.io/) integration to keep us posted with updates on dependencies.

> Or if this is not possible maybe we can discuss improving the public API for the middleware method?

The 2nd parameter expects a function that would fetch the token and return a promise. I think we could pass the store state to it without being a breaking change on the API. What do you think?

```javascript
const token = (state) => {
  return fetch('capability_token', {
      headers: { 'Authorization': `Bearer ${state.authToken}` }
  }).then((response) => response.text())
}

const createStoreWithMiddleware = applyMiddleware(
  middleware(Twilio.Device, token, {debug:true})
)(createStore)
```

**Comment by joshhornby** [comment]
> Anyhow, really glad that it's useful for anyone. PRs are always welcome and i'm open to add write access contributors if someone wants to actively maintain it.

Maybe in the future we could think about write access once I move my project into prodction? I can submit any PRs and if you have time would be very grateful for you to look over them. If you don't have time then write access would be great.

> The 2nd parameter expects a function that would fetch the token and return a promise. I think we could pass the store state to it without being a breaking change on the API. What do you think?

Sounds a good idea to me.

**Comment by yarcub** [comment]
@joshhornby yes, i can review incoming PRs.

Meanwhile, check #7
